."/*
." *  This program is free software; you can redistribute it and/or modify
." *  it under the terms of the GNU General Public License as published by
." *  the Free Software Foundation; either version 3 of the License, or
." *  (at your option) any later version.
." *
." *  This program is distributed in the hope that it will be useful,
." *  but WITHOUT ANY WARRANTY; without even the implied warranty of
." *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
." *  GNU General Public License for more details.
." *
." *  You should have received a copy of the GNU General Public License along
." *  with this program; if not, write to the Free Software Foundation, Inc.,
." *  51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
." *
." *  (C) Copyright Kevin Timmerman 2007
." *  (C) Copyright Phil Dibowitz 2007
." */
.TH "concordance" 1
.SH NAME
concordance \- for programming your Logitech Harmony remote control
.SH SYNOPSIS
.B concordance
.TP
For automatic mode:
concordance <file>
.TP
For manual mode:
concordance <options>
.SH DESCRIPTION
This software supports programming Logitech Harmony remote controls.  This software uses libusb, which requires the RAWIO capability. That means you probably need root to use it.
.TP
This software can be run in one of two modes. If you run it in automatic mode, the software will use the filename to determine what to do with it. If the filename is not *exactly* as the website sends it, then concordance will not know what to do with it, and you should use the non-automatic mode.
.TP
In command-line mode, you specify what you want to do. For any command-line option that requires updating the remote, a filename is required.
.SH OPTIONS
.TP
.B \-c, \-\-dump\-config [<filename>]
Read the config from the remote and write it to a file.  If no filename is specified, config.EZHex is used.
.TP
.B \-C, \-\-write\-config <filename>
Read a config from <filename> and write it to the remote.
.TP
.B \-f, \-\-dump\-firmware [<filename>]
Read firmware from the remote and write it to a file.  If no filename is specified firmware.EZUp is used.
.TP
.B \-F, \-\-write\-firmware <filename>
Read firmware from <filename> and write it to the remote
.TP
.B \-h, \-\-help
Print this help message and exit.
.TP
.B \-i, \-\-print\-remote\-info
Print information about the remote. Additional information will be printed if -v is also used.
.TP
.B \-k, \-\-get\-time
Get time from the remote
.TP
.B \-K, \-\-set\-time
Set the time on the remote
.TP
.B \-l, \-\-learn-ir <filename>
Learn IR from other remotes. Use <filename>.
.TP
.B \-r, \-\-reset
Reset (power-cycle) the remote control
.TP
.B \-s, \-\-dump\-safemode [<filename>]
Read the safemode firmware from the remote and write it to a file.  If no filename is specified, safe.bin is used.
.TP
.B \-t, \-\-connectivity\-test <filename>
Do a connectivity test using <filename>
.SH BUGS
None known at time of release, but check the website.
.SH BUG REPORTS
Please file all bug reports in the bugs section of our SourceForge Project page.
.SH NOTES
This software is not supported, affiliated, or controlled by Logitech in any way.
.SH AUTHOR
\fBconcordance\fP was written by Kevin Timmerman and Phil Dibowitz
.br
http://www.phildev.net/concordance/
