."/*
." * This program is free software; you can redistribute it and/or modify
." * it under the terms of the GNU General Public License as published by
." * the Free Software Foundation; either version 3 of the License, or
." * (at your option) any later version.
." *
." * This program is distributed in the hope that it will be useful,
." * but WITHOUT ANY WARRANTY; without even the implied warranty of
." * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
." * GNU General Public License for more details.
." *
." * You should have received a copy of the GNU General Public License along
." * with this program; if not, write to the Free Software Foundation, Inc.,
." * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
." *
." * (C) Copyright Kevin Timmerman 2007
." * (C) Copyright Phil Dibowitz 2007
." */
.TH "concordance" 1
.SH NAME
concordance \- for programming your Logitech Harmony remote control
.SH SYNOPSIS
.B concordance
.TP
For automatic mode:
concordance <file>
.TP
For manual mode:
concordance <options>
.SH DESCRIPTION
This software supports programming Logitech Harmony remote controls.  This software uses libconcord, which in turn uses libusb, which requires the RAWIO capability. That means you probably need root to use it.
.TP
This software can be run in one of two modes. If you run it in automatic mode, the software will analyze the file to determine what sort of file it is and what to do with it. In some cases, concordance may not be able to deteremine the filetype; if this happens, you should use manual mode.
.TP
In manual mode, you specify what you want to do. For any command-line option that requires updating the remote, a filename is required. In manual mode, you must first choose a mode (and only one):
.SH MODE-SETTING OPTIONS
.TP
.B \-c, \-\-dump\-config [<filename>]
Read the config from the remote and write it to a file.  If no filename is specified, config.EZHex is used.
.TP
.B \-C, \-\-write\-config <filename>
Read a config from <filename> and write it to the remote.
.TP
.B \-f, \-\-dump\-firmware [<filename>]
Read firmware from the remote and write it to a file.  If no filename is specified firmware.EZUp is used.
.TP
.B \-F, \-\-write\-firmware <filename>
Read firmware from <filename> and write it to the remote
.TP
.B \-h, \-\-help
Print this help message and exit.
.TP
.B \-i, \-\-print\-remote\-info
Print information about the remote. Additional information will be printed if -v is also used.
.TP
.B \-k, \-\-get\-time
Get time from the remote
.TP
.B \-K, \-\-set\-time
Set the time on the remote
.TP
.B \-l, \-\-learn-ir <filename>
Learn IR commands from other remotes. Use <filename>. When you selected multiple commands to learn on the Logitech website, you can move through this command list and let the Harmony learn the IR code for each command.
.TP
.B \-r, \-\-reset
Reset (power-cycle) the remote control
.TP
.B \-s, \-\-dump\-safemode [<filename>]
Read the safemode firmware from the remote and write it to a file.  If no filename is specified, safe.bin is used.
.TP
.B \-t, \-\-connectivity\-test <filename>
Do a connectivity test using <filename>
.TP
.B \-V, \-\-version
Print the version and exit
.TP
\fBNOTE\fP: If using the short options (e.g. -c), then *optional* arguments must be adjacent: -c/path/to/file. Required arguments don't have this limitation, and can be specified -C /path/to/file or -C/path/to/file.
.TP
Additionally, you can specify options to adjust the behavior of the software:
.SH OTHER OPTIONS
.TP
.B \-b, \-\-binary\-only
When dumping a config or firmware, this specifies to dump only the binary portion. When use without a specific filename, the default filename's extension is changed to .bin. When writing a config or firmware, this specifies the filename passed in has just the binary blob, not the XML.
.TP
.B \-\-force
Force. This forces concordance to use the file the way you specified, even if it doesn't think that's the kind of file it is. This is necessary for files dumped by concordance.
.TP
.B \-R, \-\-no\-reset
For config or firmware updates, do not reboot the device when done. This is generally only for debugging.
.TP
.B \-v, \-\-verbose
Enable verbose output.
.TP
.B \-w, \-\-no\-web
Do not attempt to talk to the website. This is useful for re-programming the remote from a saved file, or for debugging.
.TP
.SH BUGS
None known at time of release, but check the website.
.SH BUG REPORTS
Please file all bug reports in the bugs section of our SourceForge Project page.
.SH NOTES
This software is not supported, affiliated, or controlled by Logitech in any way.
.SH AUTHOR
\fBconcordance\fP was written by Kevin Timmerman and Phil Dibowitz
.br
http://www.phildev.net/concordance/
