name: Linux CI
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt-get install libcurl4-openssl-dev libhidapi-dev libzip-dev
        pip install build
    - name: Build libconcord
      run: |
        cd libconcord
        mkdir m4; autoreconf --install
        ./configure
        make
        sudo make install
        sudo ldconfig
        cd -
    - name: Build libconcord Python bindings
      run: |
        cd libconcord/bindings/python
        python3 -m build
        pip install dist/*.whl
        python3 -c 'import libconcord; print(libconcord)'
        cd -
    - name: Build concordance
      run: |
        cd concordance
        mkdir m4; autoreconf --install
        ./configure
        make
        sudo make install
        cd -
        concordance --version
