name: macOS CI
on: [push, pull_request]
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        brew install autoconf automake hidapi libzip
        pip3 install build
    - name: Build libconcord
      run: |
        cd libconcord
        mkdir m4; autoreconf --install
        ./configure
        make
        sudo make install
        cd -
    - name: Build libconcord Python bindings
      run: |
        cd libconcord/bindings/python
        python3 -m build
        pip3 install dist/*.whl
        python3 -c 'import libconcord; print(libconcord)'
        cd -
    - name: Build concordance
      run: |
        cd concordance
        mkdir m4; autoreconf --install
        ./configure
        make
        sudo make install
        cd -
        concordance --version
