name: macOS CI
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: macos-latest
    env:
      CPATH: /opt/homebrew/include
      LIBRARY_PATH: /opt/homebrew/lib
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        brew install autoconf automake hidapi libtool libzip
        pip3 install build
    - name: Build libconcord
      run: |
        cd libconcord
        mkdir m4; autoreconf --install
        ./configure
        make
        sudo make install
        cd -
    - name: Build libconcord Python bindings
      run: |
        cd libconcord/bindings/python
        python3 -m build
        pip3 install dist/*.whl
        DYLD_FALLBACK_LIBRARY_PATH=/usr/local/lib python3 -c 'import libconcord; print(libconcord)'
        cd -
    - name: Build concordance
      run: |
        cd concordance
        mkdir m4; autoreconf --install
        ./configure
        make
        sudo make install
        cd -
        concordance --version
