name: Windows CI
on:
  push:
    branches: [main]
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    container: fedora:latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: dnf install -y autoconf automake diffutils libtool mingw32-curl mingw32-gcc-c++ mingw32-hidapi mingw32-libzip mingw32-nsis python3-pip python3-wheel
    - name: Build libconcord
      run: |
        cd libconcord
        mkdir m4; autoreconf --install
        mingw32-configure
        mingw32-make
        mingw32-make install
        cd -
    - name: Build concordance
      run: |
        cd concordance
        mkdir m4; autoreconf --install
        mingw32-configure LDFLAGS="$(rpm -E %{mingw32_ldflags}) -L$(rpm -E %{mingw32_bindir})"
        mingw32-make
        mingw32-make install
        cd -
    - name: Build installer
      run: |
        pip install mingw-ldd
        MINGW_SYSROOT_BIN="/usr/i686-w64-mingw32/sys-root/mingw/bin" concordance/win/make_installer.py
    - uses: actions/upload-artifact@v2
      with:
        name: windows-installer
        path: concordance/win/concordance-installer.exe
  test:
    needs: build
    runs-on: windows-latest
    steps:
    - uses: actions/download-artifact@v2
      id: download
      with:
        name: windows-installer
    - name: Install and test
      run: |
        ${{steps.download.outputs.download-path}}\concordance-installer.exe /S
        Start-Sleep -Seconds 5
        cd "C:\Program Files (x86)\Concordance"
        .\concordance.exe --version
